background #121314
foreground #E3E2E2

# Black
color0 #1A1B1B
# Red
color1 #8383FF
# Green
color2 #64DDE5
# Yellow
color3 #75FCDD
# Blue
color4 #7AB3C5
# Magenta
color5 #7AAEEA
# Cyan
color6 #81D5E4
# White
color7 #CCDBD5

# Bright Black
color8 #B1BCB5
# Bright Red
color9 #BCB9FF
# Bright Green
color10 #F5FFFF
# Bright Yellow
color11 #FFFFFF
# Bright Blue
color12 #BFE2EB
# Bright Magenta
color13 #C8DAFF
# Bright Cyan
color14 #EFFDFF
# Bright White
color15 #DDE3E5