local opt          = vim.opt
opt.number         = true
opt.relativenumber = false
opt.tabstop        = 2
opt.shiftwidth     = 2
opt.expandtab      = true
opt.smartindent    = true
opt.ignorecase     = true
opt.smartcase      = true
opt.hlsearch       = false
opt.incsearch      = true
opt.termguicolors  = true
opt.signcolumn     = "yes"
opt.cursorline     = true
opt.scrolloff      = 8
opt.sidescrolloff  = 8
opt.wrap           = false
opt.colorcolumn    = ""
opt.splitright     = true
opt.splitbelow     = true
opt.swapfile       = false
opt.backup         = false
opt.updatetime     = 250
opt.timeoutlen     = 300
opt.clipboard      = "unnamedplus"
opt.completeopt    = "menu,menuone,noinsert,noselect"
opt.mouse          = "a"
opt.whichwrap:append("<>[]hl")
