# Fish completion for pro-mgr
# Generated by install.sh

function _pro_mgr_completion
    set -l response (env _PRO_MGR_COMPLETE=fish_complete COMP_WORDS=(commandline -cp) COMP_CWORD=(commandline -t) pro-mgr 2>/dev/null)

    for completion in $response
        set -l metadata (string split "," -- $completion)

        if test $metadata[1] = "plain"
            echo $metadata[2]
        else if test $metadata[1] = "dir"
            __fish_complete_directories $metadata[2]
        else if test $metadata[1] = "file"
            __fish_complete_path $metadata[2]
        end
    end
end

complete -c pro-mgr -f -a "(_pro_mgr_completion)"

# Manual completions for main commands
complete -c pro-mgr -n "__fish_use_subcommand" -a "new" -d "Create a new project from template"
complete -c pro-mgr -n "__fish_use_subcommand" -a "init" -d "Initialize pro-mgr.toml in existing project"
complete -c pro-mgr -n "__fish_use_subcommand" -a "run" -d "Run a task for a project"
complete -c pro-mgr -n "__fish_use_subcommand" -a "shell" -d "Print shell activation command"
complete -c pro-mgr -n "__fish_use_subcommand" -a "project" -d "Manage registered projects"
complete -c pro-mgr -n "__fish_use_subcommand" -a "snip" -d "Manage code snippets"
complete -c pro-mgr -n "__fish_use_subcommand" -a "config" -d "Manage global configuration"

# new command options
complete -c pro-mgr -n "__fish_seen_subcommand_from new" -s t -l template -d "Project template" -xa "python-cli flask-api django-app node-app dotfiles"
complete -c pro-mgr -n "__fish_seen_subcommand_from new" -s p -l path -d "Directory to create project in" -ra "(__fish_complete_directories)"
complete -c pro-mgr -n "__fish_seen_subcommand_from new" -l no-git -d "Skip Git initialization"
complete -c pro-mgr -n "__fish_seen_subcommand_from new" -l no-venv -d "Skip virtual environment creation"
complete -c pro-mgr -n "__fish_seen_subcommand_from new" -s a -l author -d "Author name for template"
complete -c pro-mgr -n "__fish_seen_subcommand_from new" -s l -l license -d "License type" -xa "MIT Apache-2.0 GPL-3.0"
complete -c pro-mgr -n "__fish_seen_subcommand_from new" -s d -l description -d "Project description"

# project subcommands
complete -c pro-mgr -n "__fish_seen_subcommand_from project" -a "list" -d "List all projects"
complete -c pro-mgr -n "__fish_seen_subcommand_from project" -a "info" -d "Show project info"
complete -c pro-mgr -n "__fish_seen_subcommand_from project" -a "add" -d "Register a project"
complete -c pro-mgr -n "__fish_seen_subcommand_from project" -a "rm" -d "Remove a project"
complete -c pro-mgr -n "__fish_seen_subcommand_from project" -a "update" -d "Update project"

# snip subcommands  
complete -c pro-mgr -n "__fish_seen_subcommand_from snip" -a "add" -d "Create a snippet"
complete -c pro-mgr -n "__fish_seen_subcommand_from snip" -a "ls" -d "List snippets"
complete -c pro-mgr -n "__fish_seen_subcommand_from snip" -a "search" -d "Search snippets"
complete -c pro-mgr -n "__fish_seen_subcommand_from snip" -a "show" -d "Show a snippet"
complete -c pro-mgr -n "__fish_seen_subcommand_from snip" -a "edit" -d "Edit a snippet"
complete -c pro-mgr -n "__fish_seen_subcommand_from snip" -a "rm" -d "Delete a snippet"

# config subcommands
complete -c pro-mgr -n "__fish_seen_subcommand_from config" -a "list" -d "List all config values"
complete -c pro-mgr -n "__fish_seen_subcommand_from config" -a "get" -d "Get a config value"
complete -c pro-mgr -n "__fish_seen_subcommand_from config" -a "set" -d "Set a config value"
complete -c pro-mgr -n "__fish_seen_subcommand_from config" -a "rm" -d "Remove a config value"